---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: blitz
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: blitz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blitz
subjects:
- kind: ServiceAccount
  name: blitz
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blitz
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-blitz-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "blitz",
      "cniVersion": "0.4.0",
      "type": "blitz",
      "dataDir": "/var/lib/cni/networks"
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-blitz-ds
  namespace: kube-system
  labels:
    tier: node
    app: blitz
spec:
  selector:
    matchLabels:
      app: blitz
  template:
    metadata:
      labels:
        tier: node
        app: blitz
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: blitz
      initContainers:
#      - name: install-cni-plugin
#        image: blitz:0.1.1-13-ge211e49-dirty
#        imagePullPolicy: Never
#        command:
#        - cp
#        args:
#        - -f
#        - /opt/bin/blitz
#        - /opt/cni/bin/blitz
#        volumeMounts:
#        - name: cni-plugin
#          mountPath: /opt/cni/bin
      - name: install-cni
        image: blitz:0.1.1-13-ge211e49-dirty
        imagePullPolicy: Never
        command:
        - cp
        args:
        - -f
        - /etc/kube-blitz/cni-conf.json
        - /etc/cni/net.d/10-blitz.conf
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: blitz-cfg
          mountPath: /etc/kube-blitz/
      - name: install-net-cfg
        image: blitz:0.1.1-13-ge211e49-dirty
        imagePullPolicy: Never
        command:
          - /opt/bin/blitzd
        args:
          - --NetworkCfgGen=true
          - --ClusterCIDR=10.244.0.0/16
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: run
            mountPath: /run/blitz
          - name: tmp
            mountPath: /tmp
      containers:
      - name: kube-blitz
        image: blitz:0.1.1-13-ge211e49-dirty
        imagePullPolicy: Never
        command:
        - /opt/bin/blitzd
        args:
        # get cluster cidr from kube-controller-manager
        - --ClusterCIDR=10.244.0.0/16
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: run
          mountPath: /run/blitz
        - name: blitz-cfg
          mountPath: /etc/kube-blitz/
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: run
        hostPath:
          path: /run/blitz
      - name: cni-plugin
        hostPath:
          path: /opt/cni/bin
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: tmp
        hostPath:
          path: /tmp
      - name: blitz-cfg
        configMap:
          name: kube-blitz-cfg
