---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tcni
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tcni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tcni
subjects:
- kind: ServiceAccount
  name: tcni
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcni
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-tcni-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "tcni",
      "cniVersion": "0.4.0",
      "type": "tcni",
      "dataDir": "/var/lib/cni/networks"
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-tcni-ds
  namespace: kube-system
  labels:
    tier: node
    app: tcni
spec:
  selector:
    matchLabels:
      app: tcni
  template:
    metadata:
      labels:
        tier: node
        app: tcni
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: tcni
      initContainers:
      - name: install-cni-plugin
        # tcni image
        image: tcni:v1.0
        command:
        - cp
        args:
        - -f
        - /tcni
        - /opt/cni/bin/tcni
        volumeMounts:
        - name: cni-plugin
          mountPath: /opt/cni/bin
      - name: install-cni
        image: tcni:v1.0
        command:
        - cp
        args:
        - -f
        - /etc/kube-tcni/cni-conf.json
        - /etc/cni/net.d/10-tcni.conf
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: tcni-cfg
          mountPath: /etc/kube-tcni/
      containers:
      - name: kube-tcni
        image: tcni:v1.0
        command:
        - /tcnid
        args:
        # get cluster cidr from kube-controller-manager
        - --cluster-cidr=10.244.0.0/16
        - --node=$(NODE_NAME)
        - --enable-iptables
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: run
          mountPath: /run/tcni
        - name: tcni-cfg
          mountPath: /etc/kube-tcni/
      volumes:
      - name: run
        hostPath:
          path: /run/tcni
      - name: cni-plugin
        hostPath:
          path: /opt/cni/bin
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: tcni-cfg
        configMap:
          name: kube-tcni-cfg
